data:
  symbols: ['ETH-BTC']
  start_date: '2023-07-01'
  end_date: '2025-01-01'
  resolution: '1h'  # Valid values: 1m, 2m, 5m, 15m, 30m, 60m, 1h, 1d, 5d, 1wk, 1mo, 3mo
  window_size: 50
  feature_window: 20

model:
  input_dim: 64
  memory_dim: 128
  num_memory_layers: 3
  num_attention_heads: 8
  dropout: 0.2

training:
  batch_size: 64
  learning_rate: 0.0001
  momentum: 0.9
  weight_decay: 0.01
  epochs: 10 