data:
  symbols: ['SPY', 'QQQ', 'IWM']
  start_date: '2010-01-01'
  end_date: '2023-12-31'
  window_size: 50
  feature_window: 20

model:
  input_dim: 5
  memory_dim: 32
  num_memory_layers: 2
  num_attention_heads: 4
  dropout: 0.1

training:
  batch_size: 32
  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 0.01 