data:
  symbols: ['SPY', 'QQQ', 'IWM']
  start_date: '2010-01-01'
  end_date: '2023-12-31'
  window_size: 50
  feature_window: 20

model:
  input_dim: 11
  memory_dim: 64
  num_memory_layers: 2
  num_attention_heads: 4
  dropout: 0.1

training:
  batch_size: 128
  learning_rate: 0.0001
  momentum: 0.9
  weight_decay: 0.01
  epochs: 10  # Number of training epochs 